# ============================================
# FWZ - Internationalization (i18n)
# ============================================

BUSINESS_PROFILE = {
    "ar": {
        "company_name": "شركة FWZ للطاقة والكهرباء",
        "intro": (
            "في FWZ نؤمن بأن الوصول إلى الخدمات الفنية يجب أن يكون سهلاً، "
            "سريعاً، وموثوقاً. لذلك بنينا منظومة متكاملة تجمع بين التنفيذ "
            "المباشر للأعمال الكهربائية وأنظمة الطاقة، وبين منصة ذكية تربط "
            "العملاء بأفضل مقدمي الخدمات الفنية في المملكة."
        ),
        "about_title": "من نحن",
        "vision_title": "رؤيتنا",
        "vision": (
            "أن نكون المنصة الأولى في المملكة العربية السعودية التي تُيسّر الوصول "
            "إلى الخدمات الفنية المتخصصة — من الكهرباء والطاقة الشمسية إلى السباكة "
            "والتكييف — بكفاءة عالية، وبيئة آمنة، وتجربة مستخدم استثنائية."
        ),
        "mission_title": "رسالتنا",
        "mission": (
            "تقديم حلول طاقة وكهرباء متكاملة عالية الجودة، وتشغيل منصة وساطة موثوقة "
            "تربط الأفراد والمنشآت بمقدمي الخدمات الفنية المؤهلين، لتحقيق تجربة خدمة "
            "سلسة ومحترفة في كل مرة."
        ),
        "system_title": "منصتك الذكية لإدارة الخدمات",
        "system_description": (
            "منصة FWZ الرقمية تتيح لك تقديم طلب خدمتك في ثوانٍ، ومتابعة تقدم "
            "التنفيذ لحظةً بلحظة، والتواصل المباشر مع فريق العمل — كل ذلك من "
            "مكان واحد بواجهة سهلة وشفافية كاملة."
        ),
        "contact_title": "تواصل معنا",
        "hq": "المملكة العربية السعودية - الرياض",
        "contact_note": "فريقنا جاهز للرد على استفساراتكم على مدار الساعة — تواصلوا معنا عبر واتساب للحصول على دعم فوري",
    },
    "en": {
        "company_name": "FWZ Energy & Electrical",
        "intro": (
            "At FWZ, we believe access to technical services should be simple, fast, and "
            "reliable. That's why we built a complete ecosystem — combining direct execution "
            "of electrical and energy projects with a smart platform that connects clients "
            "to the Kingdom's best technical service providers."
        ),
        "about_title": "About FWZ",
        "vision_title": "Our Vision",
        "vision": (
            "To be Saudi Arabia's leading platform for specialized technical services — "
            "from electrical works and solar energy to plumbing and HVAC — delivered "
            "with high efficiency, a safe environment, and an exceptional user experience."
        ),
        "mission_title": "Our Mission",
        "mission": (
            "To deliver high-quality, integrated energy and electrical solutions, and to "
            "operate a trusted marketplace that connects individuals and organizations with "
            "qualified technical service providers — ensuring a seamless, professional "
            "experience every time."
        ),
        "system_title": "Your Smart Service Management Platform",
        "system_description": (
            "The FWZ digital platform lets you submit a service request in seconds, "
            "track execution progress in real time, and communicate directly with our "
            "team — all from one place, with a simple interface and full transparency."
        ),
        "contact_title": "Get in Touch",
        "hq": "Kingdom of Saudi Arabia - Riyadh",
        "contact_note": "Our team is ready around the clock — reach us on WhatsApp for instant support and inquiries.",
    },
    "whatsapp": "+96650030287",
}

TRANSLATIONS = {
    "ar": {
        "app_title": "FWZ للطاقة والكهرباء",
        "nav_services": "خدماتنا",
        "nav_book": "اطلب خدمة",
        "nav_reviews": "التقييمات",
        "nav_login": "تسجيل الدخول",
        "nav_register": "إنشاء حساب",
        "nav_dashboard": "لوحة التحكم",
        "hero_title": "حلول طاقة وخدمات فنية متكاملة",
        "hero_sub": "نُنفّذ الأعمال الكهربائية وأنظمة الطاقة الشمسية، ونربطك بأفضل مقدمي الخدمات الفنية في المملكة — بكفاءة، وأمان، واحترافية.",
        "meta_description": "FWZ للطاقة والكهرباء — حلول متكاملة في الأعمال الكهربائية، الطاقة الشمسية، والصيانة، إلى جانب منصة وساطة تربطك بأفضل الفنيين في الكهرباء والسباكة والتكييف واللحام.",
        "meta_keywords": "FWZ, كهرباء, طاقة شمسية, صيانة, سباكة, تكييف, لحام, خدمات فنية, الرياض, السعودية, وساطة خدمات",
        "og_title": "FWZ للطاقة والكهرباء | طاقة. كهرباء. خدمات فنية.",
        "book_cta": "اطلب خدمة الآن",
        "login_title": "تسجيل الدخول",
        "login_desc": "أدخل بياناتك للوصول إلى حسابك",
        "register_title": "إنشاء حساب",
        "email": "البريد الإلكتروني",
        "password": "كلمة المرور",
        "full_name": "الاسم الكامل",
        "phone": "رقم الجوال",
        "submit": "إرسال",
        "logout": "تسجيل الخروج",
        "reset_title": "استعادة كلمة المرور",
        "reset_request": "طلب رابط الاستعادة",
        "reset_new": "تعيين كلمة مرور جديدة",
        "service": "الخدمة",
        "description": "تفاصيل الطلب",
        "location": "الموقع",
        "address": "العنوان النصي",
        "bookings": "الطلبات",
        "request": "الطلب",
        "status": "الحالة",
        "created": "تاريخ الإنشاء",
        "review": "التقييم",
        "rating": "التقييم من 1 إلى 5",
        "comment": "الملاحظة",
        "submit_review": "إرسال التقييم",
        "admin_panel": "لوحة الإدارة",
        "manage_users": "إدارة المستخدمين",
        "manage_bookings": "إدارة الطلبات",
        "manage_services": "إدارة الخدمات",
        "active_users": "المستخدمين النشطين",
        "total_bookings": "إجمالي الطلبات",
        "available_services": "الخدمات المتاحة",
        "client_reviews": "تقييمات العملاء",
        "edit": "تعديل",
        "delete": "حذف",
        "save_changes": "حفظ التغييرات",
        "cancel": "إلغاء",
        "add_new": "إضافة جديد",
        "404_title": "الصفحة غير موجودة",
        "404_message": "عذراً، الصفحة التي تبحث عنها قد تكون حذفت أو تم نقلها.",
        "back_home": "العودة للرئيسية",
        "back": "العودة للخلف",
        "switch_lang": "English",
        "successful_projects": "مشروع منجز",
        "customer_rating": "تقييم العملاء",
        "request_service": "اطلب هذه الخدمة الآن",
        "no_services": "لا توجد خدمات متاحة حالياً",
        "services_subtitle": "خدمات فنية متخصصة — من الكهرباء والطاقة الشمسية إلى السباكة والتكييف واللحام.",
        "welcome": "مرحباً",
        "filter_by": "تصفية حسب:",
        "all": "الكل",
        "new": "جديد",
        "in_progress": "قيد التنفيذ",
        "completed": "مكتمل",
        "assigned": "تم التكليف",
        "requested": "جديد",
        "cancelled": "ملغي",
        "total_requests": "إجمالي الطلبات",
        "active_requests": "قيد التنفيذ",
        "completed_requests": "طلبات مكتملة",
        "quick_actions": "إجراءات سريعة",
        "new_request": "طلب جديد",
        "home_page": "الصفحة الرئيسية",
        "profile": "الملف الشخصي",
        "settings": "الإعدادات",
        "account_settings": "إعدادات الحساب",
        "under_development": "هذه الصفحة قيد التطوير وسيتم إضافة المزيد من الخيارات قريباً.",
        "preferred_language": "اللغة المفضلة",
        "email_notifications": "تنبيهات البريد",
        "enabled": "مفعل",
        "create_account_desc": "أنشئ حسابك للبدء في استخدام خدماتنا",
        "have_account": "لديك حساب بالفعل؟",
        "no_account": "ليس لديك حساب؟",
        "forgot_password": "نسيت كلمة المرور؟",
        "detect_location": "🎯 تحديد موقعي",
        "detecting_location": "⏳ جاري التحديد...",
        "open_google_maps": "🗺️ فتح في Google Maps",
        "book_service": "حجز الخدمة",
        "select_service": "اختر الخدمة",
        "whatsapp": "واتساب",
        # Error pages
        "error_occurred": "حدث خطأ غير متوقع",
        "error_message": "نعتذر، حدث خلل فني في الخدمة. يعمل فريقنا حالياً على إصلاح المشكلة.",
        "refresh_page": "🔄 تحديث الصفحة",
        # Booking form
        "booking_desc": "أكمل البيانات التالية وحدد موقعك لنصل إليك",
        "full_name_placeholder": "الاسم الكامل",
        "address_placeholder": "الحي - الشارع - رقم المبنى",
        "description_placeholder": "اكتب وصفاً تفصيلياً للخدمة المطلوبة...",
        "password_placeholder": "كلمة مرور قوية",
        "map_hint": "💡 انقر على الخريطة أو اسحب العلامة لتحديد الموقع بدقة",
        # Loading and status
        "loading": "جاري التحميل...",
        "no_bookings": "لا توجد طلبات حتى الآن",
        "no_bookings_desc": "ابدأ بإنشاء طلب جديد للاستفادة من خدماتنا",
        "new_service_request": "طلب خدمة جديدة ✨",
        "no_description": "لا يوجد وصف إضافي",
        "default_service_desc": "نقدم أفضل خدمات الصيانة المتكاملة لضمان استمرارية أعمالكم بكفاءة عالية.",
        # Action buttons
        "accept_request": "✅ قبول الطلب",
        "start_work": "🚀 بدء التنفيذ",
        "complete_request": "✔️ إكمال الطلب",
        "cancel_request": "❌ إلغاء",
        "confirm_cancel": "هل أنت متأكد من إلغاء هذا الطلب؟",
        # Hero section
        "fast_execution": "تنفيذ سريع ومضمون",
        "team_ready": "فريق متخصص جاهز على مدار الساعة",
        "testimonial_quote": "FWZ غيّرت طريقة تعاملنا مع الخدمات الفنية — سرعة في الاستجابة، ودقة في التنفيذ، واحترافية لم نعهدها من قبل.",
        "testimonial_author": "خالد المطيري — مدير مرفق",
        # Reset password
        "reset_desc": "أدخل بريدك الإلكتروني لإعادة تعيين كلمة المرور",
        "reset_confirm_desc": "أدخل كلمة المرور الجديدة",
        "new_password_placeholder": "كلمة مرور جديدة قوية",
        "confirm_password": "تأكيد كلمة المرور",
        "confirm_password_placeholder": "أعد كتابة كلمة المرور الجديدة",
        "reset_verified_title": "تم التحقق من الرابط",
        "reset_verified_msg": "تم التحقق من رابط إعادة التعيين بنجاح. يمكنك الآن تعيين كلمة مرور جديدة.",
        "continue_reset": "متابعة إعادة التعيين",
        "remember_password": "تذكرت كلمة المرور؟",
        "no_reset_needed": "لا تحتاج إلى إعادة التعيين؟",
        # Admin panel
        "system_admin": "مدير النظام النشط",
        "back_to_dashboard": "العودة للوحة التحكم",
        "developed_by": "تم تطوير هذا التطبيق بواسطة",
        "reset_success_msg": "تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني بنجاح. يرجى التحقق من صندوق الوارد (أو البريد العشوائي).",
        "back_to_login": "العودة لتسجيل الدخول",
        "password_updated_title": "تم تحديث كلمة المرور",
        "password_updated_msg": "لقد تم تغيير كلمة المرور الخاصة بك بنجاح. يمكنك الآن تسجيل الدخول باستخدام كلمة المرور الجديدة.",
        # Navigation
        "nav_about": "من نحن",
        # Page titles
        "services_page_title": "خدماتنا",
        "about_page_title": "من نحن",
        "services_page_subtitle": "خدمات فنية متخصصة — من الكهرباء والطاقة الشمسية إلى السباكة والتكييف واللحام.",
        "view_all_services": "عرض جميع الخدمات",
        "learn_more_about": "اعرف أكثر عنّا",
        # Admin partials — services
        "admin_services_title": "إدارة كتالوج الخدمات",
        "admin_add_service": "إضافة خدمة جديدة",
        "admin_create_service_title": "إضافة خدمة جديدة للنظام",
        "admin_create_service_desc": "إدرج باقة صيانة أو خدمة فنية جديدة",
        "admin_edit_service_title": "تحديث بيانات الخدمة",
        "admin_edit_service_desc": "تعديل معلومات الخدمة",
        "insert_service_now": "إدراج الخدمة الآن",
        "service_name_ar_label": "الاسم بالعربية",
        "service_name_en_label": "الاسم بالإنجليزية",
        "service_desc_label": "وصف تفصيلي للخدمة",
        "service_name_ar_placeholder": "مثال: صيانة تكييف مركزي",
        "service_name_en_placeholder": "AC Central Maintenance",
        "service_desc_placeholder": "اشرح ما تشمله هذه الخدمة وما يميزها...",
        "no_description_available": "لا يوجد وصف تفصيلي متاح لهذه الخدمة حالياً.",
        "no_services_in_catalog": "لا توجد خدمات متاحة",
        "add_services_hint": "يمكنك البدء بإضافة باقات خدمات جديدة من خلال زر الإضافة أعلاه",
        "confirm_delete_service": "هل أنت متأكد من حذف هذه الخدمة؟ سيؤدي ذلك لحذف البيانات المرتبطة بها.",
        # Admin partials — bookings
        "admin_bookings_title": "إدارة سجل الطلبات",
        "admin_edit_booking_title": "إدارة الطلب",
        "admin_edit_booking_desc": "تغيير حالة الطلب أو تعيين موظف مسئول",
        "save_modifications": "حفظ التعديلات",
        "confirm_delete_booking": "هل أنت متأكد من حذف هذا الطلب نهائياً؟",
        "no_bookings_in_section": "لا توجد طلبات في هذا القسم",
        "bookings_appear_here": "سيظهر هنا أي طلبات جديدة بمجرد استلامها من العملاء",
        "booking_status_label": "حالة الطلب الحالية",
        "assigned_employee_label": "الموظف المكلف بالتنفيذ",
        "assign_employee_placeholder": "— اختيار الموظف —",
        "unassigned": "— غير معين —",
        "unknown_client": "عميل مجهول",
        "unknown_service": "خدمة غير محددة",
        "manage_booking_label": "إدارة الطلب",
        "delete_booking_label": "حذف الطلب",
        # Admin partials — users
        "admin_users_title": "إدارة قاعدة المستخدمين",
        "admin_add_user": "إضافة مستخدم جديد",
        "admin_create_user_title": "إضافة عضو جديد للنظام",
        "admin_create_user_desc": "إنشاء حساب جديد ببيانات كاملة",
        "admin_edit_user_title": "تحديث بيانات العضو",
        "admin_edit_user_desc": "تعديل ملف المستخدم",
        "create_account_now": "إنشاء الحساب الآن",
        "active_account": "حساب نشط",
        "user_role_label": "الدور الوظيفي",
        "user_active": "نشط",
        "user_inactive": "معطل",
        "no_users_available": "لا يوجد مستخدمين حالياً",
        "no_users_desc": "قاعدة البيانات فارغة أو لا يوجد مستخدمين يطابقون البحث",
        "confirm_delete_user": "هل أنت متأكد من حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.",
        # Table column headers
        "col_service": "الخدمة المطلوبة",
        "col_client": "العميل",
        "col_employee": "الموظف المكلف",
        "col_date": "التاريخ",
        "col_name": "الاسم الكامل",
        "col_email": "البريد الإلكتروني",
        "col_role": "الدور",
        "col_operations": "العمليات",
        "col_actions": "الإجراءات",
        # Status labels (explicit)
        "status_requested": "جديد",
        "status_assigned": "تم التكليف",
        "status_in_progress": "قيد التنفيذ",
        "status_completed": "مكتمل",
        "status_cancelled": "ملغي",
        # About page extras
        "about_hero_badge": "تأسست عام 2020",
        "contact_us_cta": "تواصل معنا",
        "our_services_cta": "خدماتنا",
    },
    "en": {
        "app_title": "FWZ Energy & Electrical",
        "nav_services": "Our Services",
        "nav_book": "Request Service",
        "nav_reviews": "Reviews",
        "nav_login": "Login",
        "nav_register": "Get Started",
        "nav_dashboard": "Dashboard",
        "hero_title": "Energy & Technical Services, Reimagined",
        "hero_sub": "We execute electrical works and solar systems directly — and connect you with top-rated technical professionals across the Kingdom. Fast, safe, and fully transparent.",
        "meta_description": "FWZ Energy & Electrical — integrated solutions in electrical works, solar energy, and maintenance, plus a trusted marketplace connecting you with specialists in plumbing, HVAC, welding, and more.",
        "meta_keywords": "FWZ, electrical, solar energy, maintenance, plumbing, HVAC, welding, technical services, Riyadh, Saudi Arabia, service marketplace",
        "og_title": "FWZ Energy & Electrical | Power. Precision. Platform.",
        "book_cta": "Request Service Now",
        "login_title": "Login",
        "login_desc": "Enter your credentials to access your account",
        "register_title": "Create Account",
        "email": "Email Address",
        "password": "Password",
        "full_name": "Full Name",
        "phone": "Phone Number",
        "submit": "Submit",
        "logout": "Logout",
        "reset_title": "Password Recovery",
        "reset_request": "Request Reset Link",
        "reset_new": "Set New Password",
        "service": "Service",
        "description": "Request Details",
        "location": "Location",
        "address": "Text Address",
        "bookings": "Bookings",
        "request": "Request",
        "status": "Status",
        "created": "Created At",
        "review": "Review",
        "rating": "Rating (1 to 5)",
        "comment": "Comment",
        "submit_review": "Submit Review",
        "admin_panel": "Admin Panel",
        "manage_users": "Manage Users",
        "manage_bookings": "Manage Bookings",
        "manage_services": "Manage Services",
        "active_users": "Active Users",
        "total_bookings": "Total Bookings",
        "available_services": "Available Services",
        "client_reviews": "Client Reviews",
        "edit": "Edit",
        "delete": "Delete",
        "save_changes": "Save Changes",
        "cancel": "Cancel",
        "add_new": "Add New",
        "404_title": "Page Not Found",
        "404_message": "Sorry, the page you are looking for may have been deleted or moved.",
        "back_home": "Back to Home",
        "back": "Go Back",
        "switch_lang": "العربية",
        "successful_projects": "Projects Delivered",
        "customer_rating": "Customer Rating",
        "request_service": "Request This Service",
        "no_services": "No services available at the moment",
        "services_subtitle": "Specialized technical services — electrical, solar energy, plumbing, HVAC, welding, and more.",
        "welcome": "Welcome",
        "filter_by": "Filter by:",
        "all": "All",
        "new": "New",
        "in_progress": "In Progress",
        "completed": "Completed",
        "assigned": "Assigned",
        "requested": "Pending",
        "cancelled": "Cancelled",
        "total_requests": "Total Requests",
        "active_requests": "In Progress",
        "completed_requests": "Completed Requests",
        "quick_actions": "Quick Actions",
        "new_request": "New Request",
        "home_page": "Home Page",
        "profile": "Profile",
        "settings": "Settings",
        "account_settings": "Account Settings",
        "under_development": "This page is under development. More options coming soon.",
        "preferred_language": "Preferred Language",
        "email_notifications": "Email Notifications",
        "enabled": "Enabled",
        "create_account_desc": "Create your account to start using our services",
        "have_account": "Already have an account?",
        "no_account": "Don't have an account?",
        "forgot_password": "Forgot your password?",
        "detect_location": "🎯 Detect Location",
        "detecting_location": "⏳ Detecting...",
        "open_google_maps": "🗺️ Open in Google Maps",
        "book_service": "Book Service",
        "select_service": "Select Service",
        "whatsapp": "WhatsApp",
        # Error pages
        "error_occurred": "An unexpected error occurred",
        "error_message": "We apologize, a technical issue has occurred. Our team is currently working to fix it.",
        "refresh_page": "🔄 Refresh Page",
        # Booking form
        "booking_desc": "Complete the following details and select your location",
        "full_name_placeholder": "Full Name",
        "address_placeholder": "District - Street - Building Number",
        "description_placeholder": "Write a detailed description of the required service...",
        "password_placeholder": "Strong password",
        "map_hint": "💡 Click on the map or drag the marker to set your exact location",
        # Loading and status
        "loading": "Loading...",
        "no_bookings": "No bookings yet",
        "no_bookings_desc": "Start by creating a new request to benefit from our services",
        "new_service_request": "Request New Service ✨",
        "no_description": "No additional description",
        "default_service_desc": "We provide the best integrated maintenance services to ensure your business continuity with high efficiency.",
        # Action buttons
        "accept_request": "✅ Accept Request",
        "start_work": "🚀 Start Work",
        "complete_request": "✔️ Complete Request",
        "cancel_request": "❌ Cancel",
        "confirm_cancel": "Are you sure you want to cancel this request?",
        # Hero section
        "fast_execution": "Fast & Guaranteed Execution",
        "team_ready": "Specialized team available 24/7",
        "testimonial_quote": "FWZ changed how we handle technical services entirely — lightning-fast response, precise execution, and a level of professionalism we hadn't seen before.",
        "testimonial_author": "Khalid Al-Mutairi — Facility Manager",
        # Reset password
        "reset_desc": "Enter your email to reset your password",
        "reset_confirm_desc": "Enter your new password",
        "new_password_placeholder": "Strong new password",
        "confirm_password": "Confirm password",
        "confirm_password_placeholder": "Re-enter your new password",
        "reset_verified_title": "Link Verified",
        "reset_verified_msg": "Your reset link is verified. You can now set a new password.",
        "continue_reset": "Continue to reset",
        "remember_password": "Remember your password?",
        "no_reset_needed": "Don't need to reset?",
        # Admin panel
        "system_admin": "Active System Administrator",
        "back_to_dashboard": "Back to Dashboard",
        "developed_by": "This app developed by",
        "reset_success_msg": "A password reset link has been sent to your email successfully. Please check your inbox (or spam folder).",
        "back_to_login": "Back to Login",
        "password_updated_title": "Password Updated",
        "password_updated_msg": "Your password has been changed successfully. You can now log in with your new password.",
        # Navigation
        "nav_about": "About",
        # Page titles
        "services_page_title": "Our Services",
        "about_page_title": "About FWZ",
        "services_page_subtitle": "Specialized technical services — electrical, solar energy, plumbing, HVAC, welding, and more.",
        "view_all_services": "View All Services",
        "learn_more_about": "Learn More About Us",
        # Admin partials — services
        "admin_services_title": "Service Catalog Management",
        "admin_add_service": "Add New Service",
        "admin_create_service_title": "Add New Service to System",
        "admin_create_service_desc": "Insert a new maintenance package or technical service",
        "admin_edit_service_title": "Update Service Details",
        "admin_edit_service_desc": "Edit service information",
        "insert_service_now": "Add Service Now",
        "service_name_ar_label": "Arabic Name",
        "service_name_en_label": "English Name",
        "service_desc_label": "Detailed Service Description",
        "service_name_ar_placeholder": "e.g. Central AC Maintenance",
        "service_name_en_placeholder": "AC Central Maintenance",
        "service_desc_placeholder": "Explain what this service includes and what makes it unique...",
        "no_description_available": "No detailed description available for this service.",
        "no_services_in_catalog": "No services available",
        "add_services_hint": "Start by adding new service packages using the button above",
        "confirm_delete_service": "Are you sure you want to delete this service? This will also delete associated records.",
        # Admin partials — bookings
        "admin_bookings_title": "Booking Records Management",
        "admin_edit_booking_title": "Manage Booking",
        "admin_edit_booking_desc": "Change booking status or assign a responsible employee",
        "save_modifications": "Save Changes",
        "confirm_delete_booking": "Are you sure you want to permanently delete this booking?",
        "no_bookings_in_section": "No bookings in this section",
        "bookings_appear_here": "New bookings from clients will appear here",
        "booking_status_label": "Current Booking Status",
        "assigned_employee_label": "Assigned Employee",
        "assign_employee_placeholder": "— Select Employee —",
        "unassigned": "— Unassigned —",
        "unknown_client": "Unknown Client",
        "unknown_service": "Service Not Specified",
        "manage_booking_label": "Manage Booking",
        "delete_booking_label": "Delete Booking",
        # Admin partials — users
        "admin_users_title": "User Management",
        "admin_add_user": "Add New User",
        "admin_create_user_title": "Add New Member to System",
        "admin_create_user_desc": "Create a new account with complete details",
        "admin_edit_user_title": "Update Member Details",
        "admin_edit_user_desc": "Edit user profile",
        "create_account_now": "Create Account Now",
        "active_account": "Active Account",
        "user_role_label": "User Role",
        "user_active": "Active",
        "user_inactive": "Inactive",
        "no_users_available": "No users at the moment",
        "no_users_desc": "The database is empty or no users match the search",
        "confirm_delete_user": "Are you sure you want to delete this user? This action cannot be undone.",
        # Table column headers
        "col_service": "Requested Service",
        "col_client": "Client",
        "col_employee": "Assigned Employee",
        "col_date": "Date",
        "col_name": "Full Name",
        "col_email": "Email Address",
        "col_role": "Role",
        "col_operations": "Operations",
        "col_actions": "Actions",
        # Status labels (explicit)
        "status_requested": "New",
        "status_assigned": "Assigned",
        "status_in_progress": "In Progress",
        "status_completed": "Completed",
        "status_cancelled": "Cancelled",
        # About page extras
        "about_hero_badge": "Founded 2020",
        "contact_us_cta": "Contact Us",
        "our_services_cta": "Our Services",
    },
}


def get_translations(lang: str = "ar") -> dict:
    """Get translations for the specified language."""
    return TRANSLATIONS.get(lang, TRANSLATIONS["ar"])


def get_profile(lang: str = "ar") -> dict:
    """Get business profile for the specified language."""
    profile = BUSINESS_PROFILE.get(lang, BUSINESS_PROFILE["ar"]).copy()
    profile["whatsapp"] = BUSINESS_PROFILE["whatsapp"]
    return profile
