"""remove price

Revision ID: 90372c868171
Revises: 0001_initial
Create Date: 2025-12-30 05:21:44.460774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90372c868171'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'price')
    op.drop_column('services', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('price', sa.FLOAT(), nullable=False))
    op.add_column('bookings', sa.Column('price', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
